# Site Information
name: your-site-name
description: 💎
author: Prince Edouard
url: ""

# Content Settings
permalink: /:categories/:title/
future: true
paginate: 12

# Azure Configuration
azure_storage:
  base_url: "https://personalwebsitemedia.blob.core.windows.net"
  container: "assets" # Assuming this is what we named your container

# Plugin Support
plugins:
  - jekyll-paginate # Required for pagination to work
