name: Prince Edouard
description: 💎
author: Prince Edouard
markdown: kramdown
pygments: false
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/Paris
paginate: 12
future: true

include: [".htaccess", "_headers", "_redirects"]

## kramdown config to force interpretation into html block
kramdown:
  parse_block_html: true

exclude: [vendor]

# add rss feed
plugins:
  - jekyll-feed
url: https://mailta.pe
repository: pedouard2/pedouard2.github.io
